"""Add storage_quota to users

Revision ID: c2d1455caee0
Revises: e5a1b2c34d78
Create Date: 2026-06-13 03:32:50.332992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d1455caee0'
down_revision: Union[str, Sequence[str], None] = 'e5a1b2c34d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_quota', sa.BigInteger(), nullable=False, server_default='5368709120'))
    op.alter_column('versions', 'is_conflict_copy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions', 'is_conflict_copy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'storage_quota')
    # ### end Alembic commands ###
