/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                      "#4edea3",
        "primary-fixed":                "#6ffbbe",
        "primary-fixed-dim":            "#4edea3",
        "primary-container":            "#10b981",
        "on-primary":                   "#003824",
        "on-primary-fixed":             "#002113",
        "on-primary-fixed-variant":     "#005236",
        "on-primary-container":         "#00422b",
        "secondary":                    "#68dba9",
        "secondary-fixed":              "#85f8c4",
        "secondary-fixed-dim":          "#68dba9",
        "secondary-container":          "#25a475",
        "on-secondary":                 "#003825",
        "on-secondary-fixed":           "#002114",
        "on-secondary-fixed-variant":   "#005137",
        "on-secondary-container":       "#00311f",
        "tertiary":                     "#ffb3af",
        "tertiary-fixed":               "#ffdad7",
        "tertiary-fixed-dim":           "#ffb3af",
        "tertiary-container":           "#fc7c78",
        "on-tertiary":                  "#650911",
        "on-tertiary-fixed":            "#410005",
        "on-tertiary-fixed-variant":    "#842225",
        "on-tertiary-container":        "#711419",
        "background":                   "#131313",
        "on-background":                "#e5e2e1",
        "surface":                      "#131313",
        "surface-dim":                  "#131313",
        "surface-bright":               "#3a3939",
        "surface-tint":                 "#4edea3",
        "surface-variant":              "#353534",
        "surface-container-lowest":     "#0e0e0e",
        "surface-container-low":        "#1c1b1b",
        "surface-container":            "#201f1f",
        "surface-container-high":       "#2a2a2a",
        "surface-container-highest":    "#353534",
        "on-surface":                   "#e5e2e1",
        "on-surface-variant":           "#bbcabf",
        "inverse-surface":              "#e5e2e1",
        "inverse-on-surface":           "#313030",
        "inverse-primary":              "#006c49",
        "outline":                      "#86948a",
        "outline-variant":              "#3c4a42",
        "error":                        "#ffb4ab",
        "error-container":              "#93000a",
        "on-error":                     "#690005",
        "on-error-container":           "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      spacing: {
        "gutter":           "24px",
        "unit":             "4px",
        "container-max":    "1440px",
        "margin-mobile":    "16px",
        "margin-desktop":   "48px",
      },
      fontFamily: {
        "body-lg":           ["Geist", "sans-serif"],
        "body-md":           ["Geist", "sans-serif"],
        "display-lg":        ["Geist", "sans-serif"],
        "headline-md":       ["Geist", "sans-serif"],
        "headline-lg":       ["Geist", "sans-serif"],
        "headline-lg-mobile":["Geist", "sans-serif"],
        "label-md":          ["JetBrains Mono", "monospace"],
        "code-sm":           ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg":            ["18px", { lineHeight: "1.6",  fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "1.6",  fontWeight: "400" }],
        "display-lg":         ["48px", { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":        ["24px", { lineHeight: "1.3",  fontWeight: "600" }],
        "headline-lg":        ["32px", { lineHeight: "1.2",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2",  fontWeight: "600" }],
        "label-md":           ["14px", { lineHeight: "1.4",  letterSpacing: "0.02em",  fontWeight: "500" }],
        "code-sm":            ["12px", { lineHeight: "1.4",  fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
