version: '3.8'

services:
  # The Database (PostgreSQL)
  db:
    image: asia-south2-docker.pkg.dev/lyrical-shore-450913-u3/shadowdrive/postgres:15
    container_name: shadow_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Storage (MinIO)
  minio:
    image: asia-south2-docker.pkg.dev/lyrical-shore-450913-u3/shadowdrive/minio:latest
    container_name: shadow_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # Code talks to this port
      - "9001:9001" # You login to this port on Chrome
    volumes:
      - minio_data:/data

  # The Job Queue (Redis) — Week 8
  redis:
    image: asia-south2-docker.pkg.dev/lyrical-shore-450913-u3/shadowdrive/redis:7-alpine
    container_name: shadow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  minio_data:
  redis_data: